### ISSUE TITLE
Todo's and stuff

### ISSUE THREAD

**Issue by CrimsonFluff** [CrimsonFluff/Crimson-Chickens#17]
- [ ] reduce spawn rate of resource chickens.  ducks in particular seem to spawn everywhere
- [ ] reduce volume of duck sounds
- [ ] add rei support
- [ ]
